package com.example.harser777.asynctaskloader1.service;

import com.example.harser777.asynctaskloader1.model.BlogPost;

import java.util.Arrays;
import java.util.List;

/**
 * Created by harser777 on 11/27/2016.
 */

public class BlogPostService {

    public List<BlogPost> getPosts() {
        //TODO: Could you imagine if this was a real service and actually hit a restful data service endpoint?
        return Arrays.asList(
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much."),
                new BlogPost("Android with maven", "blah blah blah maven rocks blah blah android this that the other thing."),
                new BlogPost("Dynamic ListView loading static ListView", "Whole lotta talking, not saying much.")
        );
    }
}